# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - arwebapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c3571a764ed14ab5a5b844138253c1d0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_da94360be7b645f2b0b09971741f78b9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c3571a764ed14ab5a5b844138253c1d0 }}/azsorlex/websiteresume-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'arwebapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_012cbbfc9562494d80183fb6632bb620 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c3571a764ed14ab5a5b844138253c1d0 }}/azsorlex/websiteresume-api:${{ github.sha }}'