name: Publish Api

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'WebsiteResume.WebApi/**'
      - 'WebsiteResume.Application/**'
      - 'WebsiteResume.Domain/**'
      - 'WebsiteResume.Infrastructure/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'WebsiteResume.WebApi/**'
      - 'WebsiteResume.Application/**'
      - 'WebsiteResume.Domain/**'
      - 'WebsiteResume.Infrastructure/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "WebsiteResume.WebApi/Dockerfile"
          push: true
          tags: azsorlex/websiteresume-api:latest
